service: jufo-gifts-backend
frameworkVersion: "2"

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1

custom:
  myStage: ${opt:stage, self:provider:stage}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

# Endpoint config
functions:
  jufoGiftsBackend:
    name: jufo-gifts-backend-${self:custom.myStage}
    handler: bin/main
    events:
      - http:
          path: /graphql
          method: post
          cors: true
