service: golan-serverless-backend
frameworkVersion: "2"
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  lambdaHashingVersion: "20201221"

package:
  patterns:
    - '!./**'
    - './bin/**'

# Endpoint config
functions:
  golangServerlessBackend:
    name: golang-serverless-backend-${sls:stage}
    handler: bin/main
    events:
      - http:
          path: /graphql
          method: post
          cors: true
